In [ ]:
pd.set_option('max_rows', 99999)
pd.set_option('max_colwidth', 4000)

In [ ]:
import pandas as pd

In [ ]:
owid = pd.read_csv('/content/drive/MyDrive/Capstone/owid/owid_covid.csv')

In [ ]:
owid

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,2020-02-24,5.0,5.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2020-02-25,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2020-02-26,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2020-02-27,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2020-02-28,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165175,ZWE,Africa,Zimbabwe,2022-02-24,234967.0,378.0,338.429,5390.0,2.0,1.286,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN
165176,ZWE,Africa,Zimbabwe,2022-02-25,235467.0,500.0,348.143,5392.0,2.0,1.000,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN
165177,ZWE,Africa,Zimbabwe,2022-02-26,235803.0,336.0,368.429,5393.0,1.0,1.000,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN
165178,ZWE,Africa,Zimbabwe,2022-02-27,235803.0,0.0,350.143,5393.0,0.0,1.000,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN
165179,ZWE,Africa,Zimbabwe,2022-02-28,236380.0,577.0,401.286,5395.0,2.0,1.286,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN

In [ ]:
#filtering not null columns from above dataset
notnull = pd.read_csv('/content/drive/MyDrive/Capstone/owid/notnull_columns.csv')

In [ ]:
notnull

,location,total_cases_start_date,total_cases_End_date,total_cases_no_of_days,new_cases_start_date,new_cases_End_date,new_cases_No. of days,total_deaths_start_date,total_deaths_end_date,total_deaths_no_of_days,...,hosp_patients_no_of_days,stringency_index_start_date,stringency_index_end_date,stringency_index_no_of_days,reproduction_rate_start_date,reproduction_rate_end_date,reproduction_rate_no_of_days,hospital_beds_per_thousand_rate_start_date,hospital_beds_per_thousand_rate_end_date,hospital_beds_per_thousand_rate_no_of_days
0,Afghanistan,2020-02-24,2022-02-28,736,2020-02-24,2022-02-28,736,2020-03-23,2022-02-28,708.0,...,NaN,2020-02-24,2022-01-31,708.0,2020-03-29,2022-02-24,698.0,2020-02-24,2022-02-28,736.0
1,Africa,2020-02-14,2022-02-28,746,2020-02-13,2022-02-28,747,2020-03-08,2022-02-28,723.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Albania,2020-03-09,2022-02-28,722,2020-03-09,2022-02-28,722,2020-03-11,2022-02-28,720.0,...,NaN,2020-02-25,2022-02-21,728.0,2020-03-24,2022-02-24,703.0,2020-02-25,2022-02-28,735.0
3,Algeria,2020-02-25,2022-02-28,735,2020-02-25,2022-02-28,735,2020-03-12,2022-02-28,719.0,...,NaN,2020-02-25,2022-02-23,730.0,2020-03-22,2022-02-24,705.0,2020-02-25,2022-02-28,735.0
4,Andorra,2020-03-02,2022-02-28,729,2020-03-02,2022-02-28,729,2020-03-22,2022-02-28,709.0,...,NaN,2020-03-02,2022-02-28,729.0,2020-03-23,2022-02-24,704.0,NaN,NaN,NaN
5,Angola,2020-03-20,2022-02-28,711,2020-03-20,2022-02-28,711,2020-03-29,2022-02-28,702.0,...,NaN,2020-03-20,2022-02-07,690.0,2020-06-11,2022-02-24,624.0,NaN,NaN,NaN
6,Anguilla,2020-03-28,2022-02-28,703,2020-03-28,2022-02-28,703,2021-09-21,2022-02-28,161.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Antigua and Barbuda,2020-03-13,2022-02-28,718,2020-03-13,2022-02-28,718,2020-04-07,2022-02-28,693.0,...,NaN,NaN,NaN,NaN,2020-09-28,2022-02-24,515.0,2020-03-13,2022-02-28,718.0
8,Argentina,2020-03-03,2022-02-28,728,2020-03-03,2022-02-28,728,2020-03-08,2022-02-28,723.0,...,NaN,2020-01-01,2022-02-21,783.0,2020-03-21,2022-02-24,706.0,2020-01-01,2022-02-28,790.0
9,Armenia,2020-03-01,2022-02-28,730,2020-03-01,2022-02-28,730,2020-03-26,2022-02-28,705.0,...,NaN,NaN,NaN,NaN,2020-03-20,2022-02-24,707.0,2020-02-03,2022-02-28,757.0
10,Aruba,2020-03-13,2022-02-28,718,2020-03-13,2022-02-28,718,2020-04-15,2022-02-28,685.0,...,NaN,2020-03-13,2022-02-24,714.0,NaN,NaN,NaN,NaN,NaN,NaN
11,Asia,2020-01-22,2022-02-28,769,2020-01-22,2022-02-28,769,2020-01-22,2022-02-28,769.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Australia,2020-01-26,2022-02-28,765,2020-01-26,2022-02-28,765,2020-03-01,2022-02-28,730.0,...,699.0,2020-01-26,2022-02-25,762.0,2020-03-11,2022-02-24,716.0,2020-01-26,2022-02-28,765.0
13,Austria,2020-02-25,2022-02-28,735,2020-02-25,2022-02-28,735,2020-03-12,2022-02-28,719.0,...,698.0,2020-02-25,2022-02-25,732.0,2020-03-09,2022-02-24,718.0,2020-02-25,2022-02-28,735.0
14,Azerbaijan,2020-03-01,2022-02-28,730,2020-03-01,2022-02-28,730,2020-03-13,2022-02-28,718.0,...,NaN,2020-03-01,2022-02-22,724.0,2020-03-27,2022-02-24,700.0,2020-03-01,2022-02-28,730.0
15,Bahamas,2020-03-16,2022-02-28,715,2020-03-16,2022-02-28,715,2020-04-01,2022-02-28,699.0,...,NaN,2020-03-16,2022-02-21,708.0,2020-05-24,2022-02-24,642.0,2020-03-16,2022-02-28,715.0
16,Bahrain,2020-02-24,2022-02-28,736,2020-02-24,2022-02-28,736,2020-03-16,2022-02-28,715.0,...,NaN,2020-02-24,2022-02-21,729.0,2020-03-11,2022-02-24,716.0,2020-02-24,2022-02-28,736.0
17,Bangladesh,2020-03-08,2022-02-28,723,2020-03-08,2022-02-28,723,2020-03-18,2022-02-28,713.0,...,NaN,2020-03-03,2022-02-12,712.0,2020-04-07,2022-02-24,689.0,2020-03-03,2022-02-28,728.0
18,Barbados,2020-03-17,2022-02-28,714,2020-03-17,2022-02-28,714,2020-04-05,2022-02-28,695.0,...,NaN,2020-03-17,2022-01-25,680.0,2020-07-12,2022-02-24,593.0,2020-03-17,2022-02-28,714.0
19,Belarus,2020-02-28,2022-02-28,732,2020-02-28,2022-02-28,732,2020-03-31,2022-02-28,700.0,...,NaN,2020-02-28,2022-02-28,732.0,2020-03-31,2022-02-24,696.0,2020-02-28,2022-02-28,732.0
20,Belgium,2020-02-04,2022-02-28,756,2020-02-04,2022-02-28,756,2020-03-11,2022-02-28,720.0,...,713.0,2020-02-04,2022-02-28,756.0,2020-03-07,2022-02-24,720.0,2020-02-04,2022-02-28,756.0
21,Belize,2020-03-23,2022-02-28,708,2020-03-23,2022-02-28,708,2020-04-06,2022-02-28,694.0,...,NaN,2020-03-23,2022-02-07,687.0,2020-08-07,2022-02-24,567.0,2020-03-23,2022-02-28,708.0
22,Benin,2020-03-16,2022-02-28,715,2020-03-16,2022-02-28,715,2020-04-06,2022-02-28,694.0,...,NaN,2020-03-16,2022-02-19,706.0,2020-05-08,2022-02-24,658.0,2020-03-16,2022-02-28,715.0
23,Bermuda,2020-03-19,2022-02-28,712,2020-03-19,2022-02-28,712,2020-04-06,2022-02-28,694.0,...,NaN,2020-03-19,2022-02-19,703.0,NaN,NaN,NaN,NaN,NaN,NaN
24,Bhutan,2020-03-06,2022-02-28,725,2020-03-06,2022-02-28,725,2021-01-08,2022-02-28,417.0,...,NaN,2020-03-06,2022-02-21,718.0,2020-07-31,2022-02-24,574.0,2020-03-06,2022-02-28,725.0
25,Bolivia,2020-03-11,2022-02-28,720,2020-03-11,2022-02-28,720,2020-03-29,2022-02-28,702.0,...,290.0,2020-03-11,2022-02-07,699.0,2020-04-01,2022-02-24,695.0,2020-03-11,2022-02-28,720.0
26,Bonaire Sint Eustatius and Saba,2020-04-02,2022-02-28,698,2020-04-02,2022-02-28,698,2020-09-16,2022-02-28,531.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Bosnia and Herzegovina,2020-03-05,2022-02-28,726,2020-03-05,2022-02-28,726,2020-03-21,2022-02-28,710.0,...,NaN,2020-03-05,2022-02-28,726.0,2020-03-23,2022-02-24,704.0,2020-03-05,2022-02-28,726.0
28,Botswana,2020-03-30,2022-02-28,701,2020-03-30,2022-02-25,698,2020-03-31,2022-02-28,700.0,...,NaN,2020-03-30,2022-02-28,701.0,2020-06-30,2022-02-24,605.0,2020-03-30,2022-02-28,701.0
29,Brazil,2020-02-26,2022-02-28,734,2020-02-26,2022-02-28,733,2020-03-17,2022-02-28,714.0,...,NaN,2020-02-26,2022-02-12,718.0,2020-03-14,2022-02-24,713.0,2020-02-26,2022-02-28,734.0
30,British Virgin Islands,2020-03-28,2022-02-28,703,2020-03-28,2022-02-28,703,2020-04-19,2022-02-28,681.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,Brunei,2020-03-09,2022-02-28,722,2020-03-09,2022-02-28,722,2020-03-28,2022-02-28,703.0,...,NaN,2020-03-09,2022-02-24,718.0,2020-03-25,2022-02-24,702.0,2020-03-09,2022-02-28,722.0
32,Bulgaria,2020-03-08,2022-02-28,723,2020-03-08,2022-02-28,723,2020-03-11,2022-02-28,720.0,...,686.0,2020-03-08,2022-02-21,716.0,2020-03-21,2022-02-24,706.0,2020-03-08,2022-02-28,723.0
33,Burkina Faso,2020-03-10,2022-02-28,721,2020-03-10,2022-02-28,721,2020-03-18,2022-02-28,713.0,...,NaN,2020-03-10,2022-02-27,720.0,2020-03-25,2022-02-24,702.0,2020-03-10,2022-02-28,721.0
34,Burundi,2020-03-31,2022-02-28,700,2020-03-31,2022-02-28,700,2020-04-13,2022-02-28,687.0,...,NaN,2020-03-31,2022-02-21,693.0,2020-06-17,2022-02-24,618.0,2020-03-31,2022-02-28,700.0
35,Cambodia,2020-01-27,2022-02-28,764,2020-01-27,2022-02-28,764,2021-03-11,2022-02-28,355.0,...,NaN,2020-01-27,2022-02-21,757.0,2020-03-30,2022-02-24,697.0,2020-01-27,2022-02-28,764.0
36,Cameroon,2020-03-06,2022-02-28,725,2020-03-06,2022-02-24,721,2020-03-25,2022-02-28,706.0,...,NaN,2020-03-06,2022-02-28,725.0,2020-03-30,2022-02-24,697.0,2020-03-06,2022-02-28,725.0
37,Canada,2020-01-26,2022-02-28,765,2020-01-26,2022-02-28,765,2020-03-09,2022-02-28,722.0,...,721.0,2020-01-26,2022-02-25,762.0,2020-03-12,2022-02-24,715.0,2020-01-26,2022-02-28,765.0
38,Cape Verde,2020-03-20,2022-02-28,711,2020-03-20,2022-02-28,711,2020-03-24,2022-02-28,707.0,...,NaN,2020-03-20,2022-02-20,703.0,2020-04-27,2022-02-24,669.0,2020-03-20,2022-02-28,711.0
39,Cayman Islands,2020-03-13,2022-02-28,718,2020-03-13,2022-02-23,713,2020-03-16,2022-02-28,715.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,Central African Republic,2020-03-15,2022-02-28,716,2020-03-15,2022-02-28,716,2020-05-23,2022-02-28,647.0,...,NaN,2020-03-15,2022-02-21,709.0,2020-05-09,2022-02-24,657.0,2020-03-15,2022-02-28,716.0
41,Chad,2020-03-19,2022-02-28,712,2020-03-19,2022-02-28,712,2020-04-28,2022-02-28,672.0,...,NaN,2020-03-19,2022-02-20,704.0,2020-05-03,2022-02-24,663.0,NaN,NaN,NaN
42,Chile,2020-02-23,2022-02-28,737,2020-02-23,2022-02-28,737,2020-03-22,2022-02-28,709.0,...,NaN,2020-02-23,2022-02-20,729.0,2020-03-16,2022-02-24,711.0,2020-02-23,2022-02-28,737.0
43,China,2020-01-22,2022-02-28,769,2020-01-23,2022-02-28,768,2020-01-22,2022-02-28,769.0,...,NaN,2020-01-22,2022-02-16,757.0,2020-01-23,2022-02-24,764.0,2020-01-22,2022-02-28,769.0
44,Colombia,2020-03-06,2022-02-28,725,2020-03-06,2022-02-28,725,2020-03-22,2022-02-28,709.0,...,NaN,2020-03-06,2022-02-28,725.0,2020-03-19,2022-02-24,708.0,2020-03-06,2022-02-28,725.0
45,Comoros,2020-04-30,2022-02-28,670,2020-04-30,2022-02-28,670,2020-05-06,2022-02-28,664.0,...,NaN,NaN,NaN,NaN,2020-05-31,2022-02-24,635.0,2020-04-30,2022-02-28,670.0
46,Congo,2020-03-15,2022-02-28,716,2020-03-15,2022-02-28,716,2020-04-02,2022-02-28,698.0,...,NaN,2020-03-15,2022-02-21,709.0,2020-04-16,2022-02-24,680.0,NaN,NaN,NaN
47,Cook Islands,2021-05-21,2022-02-28,284,2021-05-21,2022-02-28,284,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,Costa Rica,2020-03-06,2022-02-28,725,2020-03-06,2022-02-28,725,2020-03-19,2022-02-28,712.0,...,NaN,2020-03-06,2022-02-22,719.0,2020-03-22,2022-02-24,705.0,2020-03-06,2022-02-28,725.0
49,Cote d'Ivoire,2020-03-11,2022-02-28,720,2020-03-11,2022-02-28,720,2020-03-29,2022-02-28,702.0,...,NaN,2020-03-11,2022-02-13,705.0,2020-03-28,2022-02-24,699.0,NaN,NaN,NaN
50,Croatia,2020-02-25,2022-02-28,735,2020-02-25,2022-02-28,735,2020-03-19,2022-02-28,712.0,...,670.0,2020-02-25,2022-02-28,735.0,2020-03-20,2022-02-24,707.0,2020-02-25,2022-02-28,735.0
51,Cuba,2020-03-12,2022-02-28,719,2020-03-12,2022-02-28,719,2020-03-18,2022-02-28,713.0,...,NaN,2020-03-12,2022-02-07,698.0,2020-03-29,2022-02-24,698.0,2020-03-12,2022-02-28,719.0
52,Curacao,2020-03-14,2022-02-28,717,2020-03-14,2022-02-28,717,2020-03-19,2022-02-28,712.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,Cyprus,2020-03-10,2022-02-28,721,2020-03-10,2022-02-28,721,2020-03-25,2022-02-28,706.0,...,714.0,2020-03-08,2022-02-28,723.0,2020-03-25,2022-02-24,702.0,2020-03-08,2022-02-28,723.0
54,Czechia,2020-03-01,2022-02-28,730,2020-03-01,2022-02-27,729,2020-03-22,2022-02-28,709.0,...,718.0,2020-03-01,2022-02-14,716.0,2020-03-14,2022-02-24,713.0,2020-03-01,2022-02-28,730.0
55,Democratic Republic of Congo,2020-03-11,2022-02-28,720,2020-03-11,2022-02-28,720,2020-03-21,2022-02-28,710.0,...,NaN,2020-03-11,2022-02-14,706.0,2020-04-02,2022-02-24,694.0,NaN,NaN,NaN
56,Denmark,2020-02-27,2022-02-28,733,2020-02-27,2022-02-28,733,2020-03-14,2022-02-28,717.0,...,695.0,2020-02-02,2022-02-28,758.0,2020-03-11,2022-02-24,716.0,2020-02-02,2022-02-28,758.0
57,Djibouti,2020-03-18,2022-02-28,713,2020-03-18,2022-02-28,713,2020-04-10,2022-02-28,690.0,...,NaN,2020-03-18,2022-02-21,706.0,2020-04-09,2022-02-24,687.0,2020-03-18,2022-02-28,713.0
58,Dominica,2020-03-22,2022-02-28,709,2020-03-22,2022-02-28,709,2021-08-22,2022-02-28,191.0,...,NaN,2020-03-22,2022-02-10,691.0,2021-01-07,2022-02-24,414.0,2020-03-22,2022-02-28,709.0
59,Dominican Republic,2020-03-01,2022-02-28,730,2020-03-01,2022-02-28,730,2020-03-17,2022-02-28,714.0,...,NaN,2020-03-01,2022-02-21,723.0,2020-03-22,2022-02-24,705.0,2020-03-01,2022-02-28,730.0
60,Ecuador,2020-03-01,2022-02-28,730,2020-03-01,2022-02-24,726,2020-03-14,2022-02-28,717.0,...,NaN,2020-03-01,2022-02-28,730.0,2020-03-19,2022-02-24,708.0,2020-03-01,2022-02-28,730.0
61,Egypt,2020-02-14,2022-02-28,746,2020-02-14,2022-02-28,746,2020-03-08,2022-02-28,723.0,...,NaN,2020-02-14,2022-02-28,746.0,2020-03-15,2022-02-24,712.0,2020-02-14,2022-02-28,746.0
62,El Salvador,2020-03-19,2022-02-28,712,2020-03-19,2022-02-28,712,2020-03-31,2022-02-28,700.0,...,NaN,2020-03-19,2022-02-20,704.0,2020-04-10,2022-02-24,686.0,2020-03-19,2022-02-28,712.0
63,Equatorial Guinea,2020-03-15,2022-02-28,716,2020-03-15,2022-02-28,716,2020-04-22,2022-02-28,678.0,...,NaN,NaN,NaN,NaN,2020-04-25,2022-02-24,671.0,2020-03-15,2022-02-28,716.0
64,Eritrea,2020-03-21,2022-02-28,710,2020-03-21,2022-02-28,710,2020-12-22,2022-02-28,434.0,...,NaN,2020-03-21,2022-02-25,707.0,2020-06-16,2022-02-24,619.0,2020-03-21,2022-02-28,710.0
65,Estonia,2020-02-27,2022-02-28,733,2020-02-27,2022-02-28,733,2020-03-25,2022-02-28,706.0,...,730.0,2020-01-06,2022-02-11,740.0,2020-03-15,2022-02-24,712.0,2020-01-06,2022-02-28,757.0
66,Eswatini,2020-03-14,2022-02-28,717,2020-03-14,2022-02-28,717,2020-04-16,2022-02-28,684.0,...,NaN,2020-03-14,2022-02-22,711.0,2020-05-01,2022-02-24,665.0,2020-03-14,2022-02-28,717.0
67,Ethiopia,2020-03-13,2022-02-28,718,2020-03-13,2022-02-28,718,2020-04-05,2022-02-28,695.0,...,NaN,2020-03-13,2022-02-25,715.0,2020-04-19,2022-02-24,677.0,2020-03-13,2022-02-28,718.0
68,Europe,2020-01-24,2022-02-28,767,2020-01-23,2022-02-28,768,2020-02-15,2022-02-28,745.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,European Union,2020-01-24,2022-02-28,767,2020-01-23,2022-02-28,768,2020-02-15,2022-02-28,745.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,Faeroe Islands,2020-03-04,2022-02-28,727,2020-03-04,2022-02-27,726,2021-01-06,2022-02-28,419.0,...,NaN,2020-03-04,2022-02-15,714.0,NaN,NaN,NaN,NaN,NaN,NaN
71,Falkland Islands,2020-04-04,2022-02-28,696,2020-04-04,2022-02-28,696,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,Fiji,2020-03-19,2022-02-28,712,2020-03-19,2022-02-28,712,2020-07-31,2022-02-28,578.0,...,NaN,2020-01-30,2022-02-28,761.0,2021-04-27,2022-02-24,304.0,2020-01-30,2022-02-28,761.0
73,Finland,2020-01-29,2022-02-28,762,2020-01-29,2022-02-28,762,2020-03-07,2022-02-28,724.0,...,529.0,2020-01-29,2022-02-28,762.0,2020-03-12,2022-02-24,715.0,2020-01-29,2022-02-28,762.0
74,France,2020-01-24,2022-02-28,767,2020-01-24,2022-02-28,763,2020-02-15,2022-02-28,745.0,...,712.0,2020-01-24,2022-02-26,765.0,2020-03-01,2022-02-24,726.0,2020-01-24,2022-02-28,767.0
75,French Polynesia,2020-03-13,2022-02-28,718,2020-03-13,2022-02-28,718,2020-09-11,2022-02-28,536.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,Gabon,2020-03-14,2022-02-28,717,2020-03-14,2022-02-28,717,2020-03-20,2022-02-28,711.0,...,NaN,2020-03-14,2022-02-14,703.0,2020-04-18,2022-02-24,678.0,2020-03-14,2022-02-28,717.0
77,Gambia,2020-03-17,2022-02-28,714,2020-03-17,2022-02-28,714,2020-03-23,2022-02-28,708.0,...,NaN,2020-03-17,2022-02-21,707.0,2020-07-21,2022-02-24,584.0,2020-03-17,2022-02-28,714.0
78,Georgia,2020-02-26,2022-02-28,734,2020-02-26,2022-02-28,734,2020-04-04,2022-02-28,696.0,...,NaN,2020-02-26,2022-02-28,734.0,2020-03-31,2022-02-24,696.0,2020-02-26,2022-02-28,734.0
79,Germany,2020-01-27,2022-02-28,764,2020-01-27,2022-02-28,764,2020-03-09,2022-02-28,722.0,...,NaN,2020-01-27,2022-02-28,764.0,2020-03-02,2022-02-24,725.0,2020-01-27,2022-02-28,764.0
80,Ghana,2020-03-14,2022-02-28,717,2020-03-14,2022-02-28,717,2020-03-21,2022-02-28,710.0,...,NaN,2020-03-14,2022-02-27,716.0,2020-03-27,2022-02-24,700.0,2020-03-14,2022-02-28,717.0
81,Gibraltar,2020-03-04,2022-02-28,727,2020-03-04,2022-02-28,727,2020-11-11,2022-02-28,475.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,Greece,2020-02-26,2022-02-28,734,2020-02-26,2022-02-28,734,2020-03-11,2022-02-28,720.0,...,NaN,2020-01-06,2022-02-22,731.0,2020-03-14,2022-02-24,713.0,2020-01-06,2022-02-28,737.0
83,Greenland,2020-03-16,2022-02-28,715,2020-03-16,2022-02-28,715,2021-12-27,2022-02-28,64.0,...,NaN,2020-03-16,2022-02-28,715.0,NaN,NaN,NaN,NaN,NaN,NaN
84,Grenada,2020-03-22,2022-02-28,709,2020-03-22,2022-02-28,709,2021-01-03,2022-02-28,422.0,...,NaN,NaN,NaN,NaN,2020-12-21,2022-02-24,431.0,2020-03-22,2022-02-28,709.0
85,Guatemala,2020-03-14,2022-02-28,717,2020-03-14,2022-02-27,716,2020-03-16,2022-02-28,715.0,...,NaN,2020-02-17,2022-02-25,740.0,2020-04-11,2022-02-24,685.0,2020-02-17,2022-02-28,743.0
86,Guinea,2020-03-13,2022-02-28,718,2020-03-13,2022-02-28,718,2020-04-15,2022-02-28,685.0,...,NaN,2020-03-13,2022-02-26,716.0,2020-04-05,2022-02-24,691.0,2020-03-13,2022-02-28,718.0
87,Guinea-Bissau,2020-03-25,2022-02-28,706,2020-03-25,2022-02-28,706,2020-04-26,2022-02-28,674.0,...,NaN,NaN,NaN,NaN,2020-04-30,2022-02-24,666.0,NaN,NaN,NaN
88,Guyana,2020-03-12,2022-02-28,719,2020-03-12,2022-02-28,719,2020-03-12,2022-02-28,719.0,...,NaN,2020-03-12,2022-02-08,699.0,2020-05-11,2022-02-24,655.0,2020-03-12,2022-02-28,719.0
89,Haiti,2020-03-20,2022-02-28,711,2020-03-20,2022-02-28,711,2020-04-07,2022-02-28,693.0,...,NaN,2020-03-20,2022-02-27,710.0,2020-05-07,2022-02-24,659.0,2020-03-20,2022-02-28,711.0
90,High income,2020-01-22,2022-02-28,769,2020-01-22,2022-02-28,769,2020-02-04,2022-02-28,756.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91,Honduras,2020-03-11,2022-02-28,720,2020-03-11,2022-02-24,716,2020-03-26,2022-02-28,705.0,...,NaN,2020-03-11,2022-02-07,699.0,2020-03-30,2022-02-24,697.0,2020-03-11,2022-02-28,720.0
92,Hong Kong,2020-01-23,2022-02-28,768,2020-01-23,2022-02-28,768,2020-02-04,2022-02-28,756.0,...,NaN,2020-01-23,2022-02-15,755.0,NaN,NaN,NaN,NaN,NaN,NaN
93,Hungary,2020-03-04,2022-02-28,727,2020-03-04,2022-02-28,727,2020-03-15,2022-02-28,716.0,...,718.0,2020-03-03,2022-02-28,728.0,2020-03-22,2022-02-24,705.0,2020-03-03,2022-02-28,728.0
94,Iceland,2020-02-28,2022-02-28,732,2020-02-28,2022-02-28,732,2020-03-21,2022-02-28,710.0,...,475.0,2020-02-28,2022-02-28,732.0,2020-03-13,2022-02-24,714.0,2020-02-28,2022-02-28,732.0
95,India,2020-01-30,2022-02-28,761,2020-01-30,2022-02-28,761,2020-03-11,2022-02-28,720.0,...,NaN,2020-01-30,2022-02-28,761.0,2020-03-15,2022-02-24,712.0,2020-01-30,2022-02-28,761.0
96,Indonesia,2020-03-02,2022-02-28,729,2020-03-02,2022-02-28,729,2020-03-11,2022-02-28,720.0,...,NaN,2020-03-02,2022-02-28,729.0,2020-03-16,2022-02-24,711.0,2020-03-02,2022-02-28,729.0
97,International,2020-02-07,2022-02-28,753,2020-02-07,2022-02-28,753,2020-02-20,2022-02-28,740.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,Iran,2020-02-19,2022-02-28,741,2020-02-19,2022-02-28,741,2020-02-19,2022-02-28,741.0,...,NaN,2020-02-19,2022-02-25,738.0,2020-02-27,2022-02-24,729.0,2020-02-19,2022-02-28,741.0
99,Iraq,2020-02-24,2022-02-28,736,2020-02-24,2022-02-28,736,2020-03-04,2022-02-28,727.0,...,NaN,2020-02-24,2022-02-28,736.0,2020-03-14,2022-02-24,713.0,2020-02-24,2022-02-28,736.0
100,Ireland,2020-02-29,2022-02-28,731,2020-02-29,2022-02-28,731,2020-03-11,2022-02-28,720.0,...,713.0,2020-02-29,2022-02-26,729.0,2020-03-15,2022-02-24,712.0,2020-02-29,2022-02-28,731.0
101,Isle of Man,2020-03-20,2022-02-28,711,2020-03-20,2022-02-28,711,2020-04-01,2022-02-28,699.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102,Israel,2020-02-21,2022-02-28,739,2020-02-21,2022-02-28,739,2020-03-20,2022-02-28,711.0,...,728.0,2020-02-20,2022-02-25,737.0,2020-03-14,2022-02-24,713.0,2020-02-20,2022-02-28,740.0
103,Italy,2020-01-31,2022-02-28,760,2020-01-31,2022-02-28,760,2020-02-21,2022-02-28,739.0,...,735.0,2020-01-31,2022-02-25,757.0,2020-02-24,2022-02-24,732.0,2020-01-31,2022-02-28,760.0
104,Jamaica,2020-03-11,2022-02-28,720,2020-03-11,2022-02-28,720,2020-03-19,2022-02-28,712.0,...,NaN,2020-03-11,2022-02-21,713.0,2020-04-16,2022-02-24,680.0,2020-03-11,2022-02-28,720.0
105,Japan,2020-01-22,2022-02-28,769,2020-01-23,2022-02-28,768,2020-02-13,2022-02-28,747.0,...,96.0,2020-01-22,2022-02-25,766.0,2020-02-22,2022-02-24,734.0,2020-01-22,2022-02-28,769.0
106,Jordan,2020-03-03,2022-02-28,728,2020-03-03,2022-02-28,728,2020-03-27,2022-02-28,704.0,...,NaN,2020-03-03,2022-02-21,721.0,2020-03-23,2022-02-24,704.0,2020-03-03,2022-02-28,728.0
107,Kazakhstan,2020-03-13,2022-02-28,718,2020-03-13,2022-02-28,718,2020-03-27,2022-02-28,704.0,...,NaN,2020-03-13,2022-01-24,683.0,2020-03-27,2022-02-24,700.0,2020-03-13,2022-02-28,718.0
108,Kenya,2020-03-13,2022-02-28,718,2020-03-13,2022-02-28,718,2020-03-26,2022-02-28,705.0,...,NaN,2020-03-06,2022-02-22,719.0,2020-04-03,2022-02-24,693.0,2020-03-06,2022-02-28,725.0
109,Kiribati,2021-05-18,2022-02-28,287,2021-05-18,2022-02-28,287,2022-02-09,2022-02-28,20.0,...,NaN,2021-05-18,2022-02-28,287.0,2022-01-27,2022-02-24,29.0,2021-05-18,2022-02-28,287.0
110,Kosovo,2020-03-14,2022-02-28,717,2020-03-14,2022-02-28,717,2020-03-23,2022-02-28,708.0,...,NaN,2020-03-14,2022-02-21,710.0,2020-04-01,2022-02-24,695.0,NaN,NaN,NaN

In [ ]:
# all columns in OWID dataset
owid.columns

Index(['iso_code', 'continent', 'location', 'date', 'total_cases', 'new_cases',
       'new_cases_smoothed', 'total_deaths', 'new_deaths',
       'new_deaths_smoothed', 'total_cases_per_million',
       'new_cases_per_million', 'new_cases_smoothed_per_million',
       'total_deaths_per_million', 'new_deaths_per_million',
       'new_deaths_smoothed_per_million', 'reproduction_rate', 'icu_patients',
       'icu_patients_per_million', 'hosp_patients',
       'hosp_patients_per_million', 'weekly_icu_admissions',
       'weekly_icu_admissions_per_million', 'weekly_hosp_admissions',
       'weekly_hosp_admissions_per_million', 'new_tests', 'total_tests',
       'total_tests_per_thousand', 'new_tests_per_thousand',
       'new_tests_smoothed', 'new_tests_smoothed_per_thousand',
       'positive_rate', 'tests_per_case', 'tests_units', 'total_vaccinations',
       'people_vaccinated', 'people_fully_vaccinated', 'total_boosters',
       'new_vaccinations', 'new_vaccinations_smoothed',
       'total_vaccinations_per_hundred', 'people_vaccinated_per_hundred',
       'people_fully_vaccinated_per_hundred', 'total_boosters_per_hundred',
       'new_vaccinations_smoothed_per_million',
       'new_people_vaccinated_smoothed',
       'new_people_vaccinated_smoothed_per_hundred', 'stringency_index',
       'population', 'population_density', 'median_age', 'aged_65_older',
       'aged_70_older', 'gdp_per_capita', 'extreme_poverty',
       'cardiovasc_death_rate', 'diabetes_prevalence', 'female_smokers',
       'male_smokers', 'handwashing_facilities', 'hospital_beds_per_thousand',
       'life_expectancy', 'human_development_index',
       'excess_mortality_cumulative_absolute', 'excess_mortality_cumulative',
       'excess_mortality', 'excess_mortality_cumulative_per_million'],
      dtype='object')

In [ ]:
#description of all not null columns
notnull.columns

Index(['location', 'total_cases_start_date', 'total_cases_End_date',
       'total_cases_no_of_days', 'new_cases_start_date', 'new_cases_End_date',
       'new_cases_No. of days', 'total_deaths_start_date',
       'total_deaths_end_date', 'total_deaths_no_of_days',
       'new_deaths_start_date', 'new_deaths_end_date', 'new_deaths_no_of_days',
       'total_tests_start_date', 'total_tests_end_date',
       'total_tests_no_of_days', 'new_tests_start_date', 'new_tests_end_date',
       'new_tests_no_of_days', 'positive_rate_start_date',
       'positive_rate_end_date', 'positive_rate_no_of_days',
       'tests_per_case_start_date', 'tests_per_case_end_date',
       'tests_per_case_no_of_days', 'total_vaccinations_start_date',
       'total_vaccinations_end_date', 'total_vaccinations_no_of_days',
       'people_vaccinated_start_date', 'people_vaccinated_end_date',
       'people_vaccinated_no_of_days', 'people_fully_vaccinated_start_date',
       'people_fully_vaccinated_end_date',
       'people_fully_vaccinated_no_of_days', 'total_boosters_start_date',
       'total_boosters_end_date', 'total_boosters_no_of_days',
       'new_vaccinations_start_date', 'new_vaccinations_end_date',
       'new_vaccinations_no_of_days', 'icu_patients_start_date',
       'icu_patients_end_date', 'icu_patients_no_of_days',
       'hosp_patients_start_date', 'hosp_patients_end_date',
       'hosp_patients_no_of_days', 'stringency_index_start_date',
       'stringency_index_end_date', 'stringency_index_no_of_days',
       'reproduction_rate_start_date', 'reproduction_rate_end_date',
       'reproduction_rate_no_of_days',
       'hospital_beds_per_thousand_rate_start_date',
       'hospital_beds_per_thousand_rate_end_date',
       'hospital_beds_per_thousand_rate_no_of_days'],
      dtype='object')

In [ ]:
#filtering new cases of India data
india_new_cases =  owid[owid['location']=='India'][['date','new_cases']]

In [ ]:
india_new_cases.shape

(761, 2)

In [ ]:
#saving data in new csv file
india_new_cases.to_csv('/content/drive/MyDrive/Capstone/india_new_cases', index=False)